In [ ]:
#                                               [ARRAY]

In [ ]:
#  Numpy package
#  numpy= Numerical python- Sokol calculation r kaj kora hoy eta diye
#  array akare kaj kore .

In [ ]:
# import  = pre install kora thakbe sudu import korte hobe
# install = install kore nite hobe

In [ ]:
# import numpy as np

In [ ]:
#                        -----------------------1D array using numpy----------------------------

In [ ]:
#    There are 4 way use to create 1D array

In [ ]:
#                                              Way-----(1)

In [1]:
                     import numpy as np
                     a= np.array([2,4,6,8])
                     print (a)

[2 4 6 8]


In [3]:
                     import numpy as np
                     b= np.array([2,4,6.5,8.99])
                     print (b)

[2.   4.   6.5  8.99]


In [ ]:
#                                              Way----(2) linspace (Start, stop,n)

In [19]:
                     import numpy as np
                     L= np.linspace(2,4,6,8,10)
                     print (L)

(array([2. , 2.4, 2.8, 3.2, 3.6, 4. ]), 0.4)


In [ ]:
#                                                   Way-----(3) arange (Start, stop,stepsize)

In [25]:
                     import numpy as np
                     A = np.arange(10)
                     print (A)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
                     import numpy as np
                     A = np.arange(100)
                     print (A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
#                                               Way----(4) ones(), zeros()

In [29]:
                    import numpy as np
                    K = np.zeros(5)
                    print (K)

[0. 0. 0. 0. 0.]


In [31]:
                    import numpy as np
                    K = np.ones(5)
                    print(K)

[1. 1. 1. 1. 1.]


In [ ]:
#                                           Mathematical operation an array

In [60]:
import numpy as np
k= np.array([1,2,3,4,5])
print (k)
k+5
k-5
k*5
k/5

[1 2 3 4 5]


array([0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
#                         -----------------------2D array using numpy----------------------------

In [66]:
import numpy as np
x= np.array([[2,4,6,8],[10,12,14,16]])
print (x)

[[ 2  4  6  8]
 [10 12 14 16]]


In [62]:
#                         -----------------------2D array using numpy----------------------------

In [ ]:
#                              ndim attibute (Show number of array)

In [78]:
import numpy as np
x= np.array([[2,4,6,8],[10,12,14,16]])
y= np.array([[2,4,6,8],[10,12,14,16],[2,3,2,2]])
print (x.ndim)
print (y.ndim)

2
2


In [ ]:
# Shape attribute

In [82]:
import numpy as np
x= np.array([[2,4,6,8],[10,12,14,16]])
y= np.array([[2,4,6,8],[10,12,14,16],[2,3,2,2]])
print (x.shape)
print (y.shape)

(2, 4)
(3, 4)


In [ ]:
# size attribute

In [84]:
import numpy as np
x= np.array([[2,4,6,8],[10,12,14,16]])
y= np.array([[2,4,6,8],[10,12,14,16],[2,3,2,2]])
print (x.size)
print (y.size)

8
12


In [ ]:
# reshape attribute

In [88]:
import numpy as np
y= np.array([[2,4,6,8],[10,12,14,16],[2,3,2,2]])
z= y.reshape(6,2)
print (z)

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [ 2  3]
 [ 2  2]]


In [ ]:
# concatenate (join more then one array)

In [94]:
import numpy as np
x= np.array([[2,4,6,8],[10,12,14,16]])
y= np.array([[2,4,6,8],[10,12,14,16]])
z= np.concatenate([x,y])
print(z)


[[ 2  4  6  8]
 [10 12 14 16]
 [ 2  4  6  8]
 [10 12 14 16]]


In [ ]:
# hstack attribute (joint horizontally)